FROM mcr.microsoft.com/powershell:ubuntu-16.04

RUN apt update && apt upgrade -y
RUN apt install ansible git -y
RUN apt install docker -y

RUN mkdir /builder && mkdir /builder/src && mkdir /builder/artifacts

VOLUME ["/builder/src", "/builder/artifacts"] 

CMD bash