FROM ubuntu:18.10

RUN apt-get update -y && dpkg --add-architecture i386 && apt-get install wget -y && wget -nc https://dl.winehq.org/wine-builds/winehq.key \
    && apt-key add winehq.key \
    && apt-add-repository 'deb https://dl.winehq.org/wine-builds/ubuntu/ cosmic main' \
    && apt-get install --install-recommends winehq-stable -y \
    && winecfg

COPY ../runtimes /